ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50g
  host: 'books.rabarbra.me'
  path: /
  pathType: 'Prefix'
  tls:
   - secretName: readarr-tls
     hosts:
       - books.rabarbra.me

persistentVolumeClaims:
  readarr-config:
    requestStorage: '100Mi'
    selector: {}
