apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readarr
  namespace: argocd
spec:
  project: apps
  sources:
  - repoURL: https://media-servarr.shw.al/charts/
    chart: readarr
    targetRevision: "0.7.0"
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 50g
          host: 'books.rabarbra.me'
          path: /
          pathType: 'Prefix'
          tls:
          - secretName: readarr-tls
            hosts:
              - books.rabarbra.me

        persistentVolumeClaims:
          readarr-config:
            requestStorage: '100Mi'
            selector: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: readarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
