apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  project: apps
  sources:
  - repoURL: https://utkuozdemir.org/helm-charts/
    chart: filebrowser
    targetRevision: "1.0.0"
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 50g
          hosts:
            - host: files.rabarbra.me
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: filebrowser-tls
            hosts:
              - files.rabarbra.me
        rootDir:
          type: pvc
          readOnly: false
          hostPath:
            path: /
          pvc:
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            size: 2Gi
        db:
          pvc:
            enabled: true
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            size: 256Ki
        config:
          port: 8080
          baseURL: ""
          address: ""
          log: stdout
          database: /db/database.db
          root: /rootdir
  destination:
    server: https://kubernetes.default.svc
    namespace: filebrowser
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
