apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: apps
  sources:
  - repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: "10.5.0"
    helm:
      valuesObject:
        gitea:
        postgresql:
          enabled: true
          primary:
            persistence:
              size: 5Gi
        postgresql-ha:
          enabled: false
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 50m
          className: nginx
          hosts:
            - host: git.rabarbra.me
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
              - git.rabarbra.me
              secretName: gitea-tls
        persistence:
          enabled: true
        redis-cluster:
          enabled: false
        redis:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
