apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-tty
  namespace: argocd
spec:
  project: apps
  sources:
  - repoURL: https://rabarbra.github.io/charts/
    chart: web-tty
    targetRevision: "0.1.0"
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: contour
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: sh.rabarbra.me
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: web-tty-tls
            hosts:
              - sh.rabarbra.me
  destination:
    server: https://kubernetes.default.svc
    namespace: web-tty
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
