apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: jupyter
spec:
  project: default
  sources:
  - repoURL: https://github.com/rabarbra/k8s-argo-apps.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://hub.jupyter.org/helm-chart/
    chart: jupyterhub
    targetRevision: "3.3.8"
    helm:
      valueFiles:
        - $values/apps/jupyter/envs/prod/values-prod.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
