gitea:
  config:
    database:
      DB_TYPE: mysql
      HOST: mysql:3306
      NAME: gitea
      USER: Unclad
      PASSWD: "ssP7n9v&$2hKYb4Mqy2uHecTbD"

postgresql:
  enabled: false

postgresql-ha:
  enabled: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  className: nginx
  hosts:
    - host: git.rabarbra.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - jupyter.rabarbra.me
      secretName: gitea-tls

persistence:
  enabled: false