apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://utkuozdemir.org/helm-charts/
    chart: filebrowser
    targetRevision: "1.0.0"
    helm:
      valueFiles:
        - $values/apps/filebrowser/envs/prod/values.yaml
  - repoURL: https://github.com/rabarbra/k8s-argo-apps.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: filebrowser
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
